name: Commit Builde
on:
  push:
    branches:
      - master

jobs:
  publishing:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
        python-version: [3.8]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Prepare variables
        run: |
          export COMMIT_ID="$(git log --format=%H -n 1)"
          export COMMIT_MSG="$(git log --format=%B -n 1)"
      - name: Build Main and Rest Modules
        run: |
          bash ./build.sh
      - name: Publish Components
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run:
          echo "=================================="
          echo "Commit ID: ${COMMIT_ID}"
          echo "COMMIT_MSG: ${COMMIT_MSG}"
          echo "=================================="
          twine upload -r pypi -u "${TWINE_USERNAME}" -p "${TWINE_PASS}" -c "${COMMIT_MSG} (${COMMIT_ID})" --skip-existing ./dist/*